# stellar-blaster configuration example
# Each endpoint can be configured with:
#   rps          - requests per second
#   [data_path]  - path to JSON data for parameters

# No-parameter/run-only endpoints
[endpoints.getHealth]
rps = 20

[endpoints.getNetwork]
rps = 20

[endpoints.getVersionInfo]
rps = 20

[endpoints.getLatestLedger]
rps = 20

[endpoints.getFeeStats]
rps = 20

# Parameter-based/generate-required endpoints
[endpoints.getEvents] # this only takes optional arguments
rps = 20
data_path = "output/seed.json"

[endpoints.getLedgerEntries]
rps = 20
data_path = "output/seed.json"

[endpoints.getLedgers]
rps = 20
data_path = "output/seed.json"

[endpoints.getTransaction]
rps = 20
data_path = "output/seed.json"

[endpoints.getTransactions]
rps = 20
data_path = "output/seed.json"
